# Generated by Django 3.0.5 on 2020-04-19 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitanicDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.CharField(max_length=3)),
                ('sex', models.CharField(max_length=3)),
                ('age', models.CharField(max_length=2)),
                ('sibhp', models.CharField(max_length=3)),
                ('parch', models.CharField(max_length=3)),
                ('fare', models.CharField(max_length=3)),
                ('mbarked', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=30)),
                ('skl_result', models.CharField(max_length=3)),
                ('nn_result', models.CharField(max_length=3)),
                ('completed', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
