# Generated by Django 3.0.5 on 2020-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0002_auto_20200419_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='titanicdb',
            name='nn_rate',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='age',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='fare',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='mbarked',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='nn_result',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='parch',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='pclass',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='sex',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='sibhp',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='skl_result',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='titanicdb',
            name='title',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
